//
// Created by coolder on 4/14/21.
//

#ifndef SOCK_AUTH_SERVER_TRANSFER_H
#define SOCK_AUTH_SERVER_TRANSFER_H

#endif //SOCK_AUTH_SERVER_TRANSFER_H

#ifndef TRANSFER_FILE_TRANSFER_H
#define TRANSFER_FILE_TRANSFER_H

#define MAX_LINE 4096
#define LINSTENPORT 7788
#define SERVERPORT 8877
#define BUFFSIZE 4096

#endif //TRANSFER_FILE_TRANSFER_H
