/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_company_Main */

#ifndef _Included_com_company_Main
#define _Included_com_company_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_company_Main
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_company_Main_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
