theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} updates available"
format_singular = "{pacman} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux |linux-lts|linux-zen)"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}° avg"
chip = "*-isa-*"
inputs = ["CPUTIN", "SYSTIN"]

[[block]]
block = "net"
device = "wlp3s0"
format = "{speed_down}"
interval = 5
use_bits = false
